version: '3'
services:
  mysql:
    image: mysql:8.0.36
    platform: linux/amd64
    env_file: ./env/mysql.env
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 3306:3306

  app:
    image: andersonmarquesdocker/codechella:1.0
    platform: linux/amd64
    env_file: ./env/app.env
    restart: unless-stopped
    depends_on:
      - mysql

  nginx:
    image: nginx:1.21.3
    platform: linux/amd64
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: unless-stopped
    depends_on:
      - app

  redis:
    image: redis:7.2.4
    restart: unless-stopped
    ports:
      - 6379:6379

volumes:
  mysql-data:
