spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codechella?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  security:
    jwt:
      secret: 12345678
