spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codechella?createDatabaseIfNotExist=true
    username: codechella_user
    password: codechella_pwd

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: redis
    port: 6379

app:
  security:
    jwt:
      secret: 12345678
