name: Test Secrets

on:
  push:
    branches:
      - main

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug Secret Length
        run: echo "${#DOCKERHUB_TOKEN}"
        env:
          DOCKERHUB_TOKEN: ${{ secrets.TEST_SECRET }}
